server:
  port: 9002

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Reza-Moein-21/application-configurations.git
          default-label: liv

eureka:
  client:
    serviceUrl:
      defaultZone: http://10.10.1.1:9001/eureka
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: health,info